---
title: "Comparing Susceptibility and Resiliency of Functional Connectivity Between Visual and Default Mode Resting State Networks"
output: html_notebook
---


```{r Load dependencies, if not already loaded}

dependencies <- c(
  "tidyr",
  "dplyr",
  "stringr",
  "cocor"
)

for (package in dependencies) {
  if (!package %in% (.packages())) {
    library(package,
            character.only = T)
  }
}

if (!exists("fcDev")) {
  source('scripts/getData.R')
  source('scripts/preprocessing.R')
}

```

```{r Read in regions}

visual <- read.table('../data/SmithVisualNetwork.txt',
                     col.names = "regions",
                     header = F,
                     encoding = "utf-8")

dmn <- read.table('../data/SmithDMN.txt',
                  col.names = "regions",
                  header = F,
                  encoding = "utf-8") %>%
  filter(regions != "superiorfrontal")


```

```{r Create dataframe of only the columns in a specific network}

isolateNetworkPairs <- function(network, inputData) {
  
  networkData <- data.frame(row.names = rownames(inputData))
  
  for (region in network$regions) {
    networkData <- cbind(
      inputData[, grep(region, names(inputData))],
      networkData
    )
  }
  
  return (networkData)
  
}

```

```{r Functional networks}

visual.fcDev <- isolateNetworkPairs(visual, fcDev)
dmn.fcDev <- isolateNetworkPairs(dmn, fcDev)

```
``` {r Structural networks}

visual.discon <- isolateNetworkPairs(visual, discon)
dmn.discon <- isolateNetworkPairs(dmn, discon)

```

```{r Quick Visualization Function}

quickScatterPlot <- function(fc.input, discon.input, network) {
  
  model <- lm(
    fc.input ~ discon.input
  )
  
  rsq <- summary(model)$r.square
  
  pval <- str_split(
    summary(model)[4], " ", simplify = T)[8]
  
  ggplot() +
    geom_point(
      aes(x = discon.input,
          y = fc.input)
    ) + 
    labs(title = network,
         x = "Structural Disconnection within Network",
         y = "Change in Functional Connectivity within Network") + 
    geom_label(
      aes(x = Inf,
          y = Inf,
          label = paste("R2 = ",rsq)),
      inherit.aes = F,
      hjust = "inward",
      vjust = "inward"
    ) + 
    geom_label(
      aes(x = Inf,
          y = -Inf,
          label = paste("P = ",pval)),
      inherit.aes = F,
      hjust = "inward",
      vjust = "inward"
    )
  
}

```


```{r Visual: Plot sum of structural disconnection vs sum of functional deviation}

subjects <- intersect(rownames(visual.fcDev),
                      rownames(visual.discon))

quickScatterPlot(rowSums(visual.fcDev[subjects,]), rowSums(visual.discon[subjects,]), "Visual")

```

```{r Visual: Plot sum of structural disconnection vs sum of functional deviation}

quickScatterPlot(apply(visual.fcDev[subjects,], 1, mean),
                 apply(visual.discon[subjects,], 1, mean),
                 "Visual")

```

```{r DMN: Plot sum of structural disconnection vs sum of functional deviation}

quickScatterPlot(rowSums(dmn.fcDev[subjects,]), rowSums(dmn.discon[subjects,]), "Default Mode Network")

```

```{r DMN: Plot sum of structural disconnection vs sum of functional deviation}

quickScatterPlot(apply(dmn.fcDev[subjects,], 1, mean),
                 apply(dmn.discon[subjects,], 1, mean),
                 "Default Mode Network")

```

```{r Test that the correlations of the two networks are different}

cocor.indep.groups(
    cor(rowSums(visual.discon[subjects,]), rowSums(visual.fcDev[subjects,])),
    cor(rowSums(dmn.discon[subjects,]), rowSums(dmn.fcDev[subjects,])),
    length(subjects),
    length(subjects),
    alternative = "g"
)

```

```{r}

cocor.indep.groups(
    cor(apply(visual.fcDev[subjects,], 1, mean), apply(visual.discon[subjects,], 1, mean)),
    cor(apply(dmn.fcDev[subjects,], 1, mean), apply(dmn.discon[subjects,], 1, mean)),
    length(subjects),
    length(subjects),
    alternative = "g"
)

```

